In [2]:
import numpy as np
import pandas as pd

merging two dataFrame

In [4]:
employee = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name' : ['John','Anna','Peter','Linda','Bob'],
    'department' : ['HR','IT','Finance','IT','HR']
})
salaries = pd.DataFrame({
    'employee_id' : [1,2,3,6,7],
    'salary' : [60000,80000,65000,70000,90000],
    'bonus' : [5000,10000,7000,8000,12000]
})

In [6]:
employee

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [7]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [10]:
pd.merge(employee,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [12]:
pd.merge(employee,salaries,on = 'employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [13]:
pd.merge(employee,salaries,on = 'employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [14]:
pd.merge(employee,salaries,on = 'employee_id',how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [15]:
pd.merge(employee,salaries,on = 'employee_id',how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [16]:
pd.merge(employee,salaries,on = 'employee_id',how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of 2 dataframes

In [17]:
df1 = pd.DataFrame({
    
    'A' : ['A0','A1','A2'],
    'B' : ['B0','B1','B2'],
    'C' : ['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A' : ['A3','A4','A5'],
    'B' : ['B3','B4','B5'],
    'C' : ['C3','C4','C5']
})

In [18]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [19]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [20]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [21]:
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

joining 2 data frames

In [3]:
df1 = pd.DataFrame({
    
    'name' : ['Alice', 'Bob','Charlie']
},index = [1,2,3])

df2 = pd.DataFrame({
    'Score' : [85,90,75]
    
},index = [2,3,4])

In [4]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [5]:
df2

   Score
2     85
3     90
4     75

In [6]:
df1.join(df2)

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [7]:
df1.join(df2,how = 'outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0