In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "Income" : [12000,13000,0,34000,67000]
}
df = pd.DataFrame(data)

In [4]:
df

   Income
0   12000
1   13000
2       0
3   34000
4   67000

In [5]:
df["Income_log"] = np.log1p(df["Income"])

In [6]:
df

   Income  Income_log
0   12000    9.392745
1   13000    9.472782
2       0    0.000000
3   34000   10.434145
4   67000   11.112463