In [1]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    "Employee_ID" : [101,102,102,103,104,105,106],
    "Age" : [28,34,34,-5,120,np.nan,45], #invalid : duplicate,negative,extreme,missing
    "Salary" : [50000,60000,60000,55000,70000,80000,-1000],  # invalid : negative salary
    "Department" : ["IT","HR","HR","Marketin","IT","Sales","HR"]     


}
df = pd.DataFrame(data)

In [5]:
df

   Employee_ID    Age  Salary Department
0          101   28.0   50000         IT
1          102   34.0   60000         HR
2          102   34.0   60000         HR
3          103   -5.0   55000   Marketin
4          104  120.0   70000         IT
5          105    NaN   80000      Sales
6          106   45.0   -1000         HR

In [6]:
duplicate_count = df.duplicated().sum()

In [7]:
df_cleaned = df.drop_duplicates().copy()

In [11]:
df_cleaned.head()

   Employee_ID    Age  Salary Department
0          101   28.0   50000         IT
1          102   34.0   60000         HR
3          103   -5.0   55000   Marketin
4          104  120.0   70000         IT
5          105    NaN   80000      Sales